### ISSUE TITLE
Pet profile

### ISSUE THREAD

**Issue by nikkypyra** [nikkypyra/capstone-project#1]
### Value Statement: 
As a **pet owner**, 
I need to **create individual profiles for my pets** 
to **keep track of their daily requirements**.

### Description: 
an individual pet profile page with a list of their daily requirements
<img width="558" alt="Story1" src="https://user-images.githubusercontent.com/57285588/80625755-f2de6f00-8a4d-11ea-91a5-6fcf15fec742.png">

### Acceptance criteria:
- [x] The page is found at the path “/pet-profile”
- [x] Profile page includes photo and name of pet
- [x] Profile page includes daily requirements
- [x] Page scrolls vertically
- [x] Page items are visually separated

### Tasks:
- [x] Create feature branch
- [x] Add PetProfile component to app
- [x] Add routing
- [x] Create tasks.json
- [x] Create component in Storybook
- [x] Add style
- [x] Test on mobile and desktop

### Size: 
medium
