### ISSUE TITLE
Individualize pet pages and tasks

### ISSUE THREAD

**Issue by nikkypyra** [nikkypyra/capstone-project#14]
### Value Statement: 
As a **user**, 
I need to **assign specific tasks to specific pets** 
to **keep their schedules organized**.

### Description: 
 individual profile pages with specific tasks to that pet

### Acceptance criteria:
- [x] A page is created for each newly added pet
- [x] Tasks can be assigned to an individual pet
- [x] Each pet page can be visited from the Home page

### Tasks:
- [x] Create feature branch
- [x] Add task-pet logic
- [x] Add Router
- [x] Add style
- [x] Test on mobile

### Size: 
large
