### ISSUE TITLE
Sort tasks by date and time

### ISSUE THREAD

**Issue by nikkypyra** [nikkypyra/capstone-project#16]
### Value Statement: 
As a **user**, 
it would be most convenient **to have my pets' tasks sorted by date and time** 
so that I **have an organized overview of the tasks to be completed each day**.

### Description: 
 previously existing task list ordered by date, then time

### Acceptance criteria:
- [x] Tasks are sorted properly by date and time on each pet's page

### Tasks:
- [x] Create feature branch
- [x] Add sort methods for date and time
- [x] Add testing
- [x] Test on mobile

### Size: 
small
