### ISSUE TITLE
Filter tasks

### ISSUE THREAD

**Issue by nikkypyra** [nikkypyra/capstone-project#18]
### Value Statement: 
As a **user**, 
I need to **be able to search for tasks to be completed on a certain date or by a certain person** 
to **stay organized**.

### Description: 
 a search page with all available tasks shown until filtered by date or person
<img width="367" alt="filter" src="https://user-images.githubusercontent.com/57285588/81542506-0a362a00-9375-11ea-9250-0f0da0a47920.png">

### Acceptance criteria:
- [x] The page is found at the path "/filter"
- [x] Tasks are filtered by date or person
- [x] Tasks are then sorted by date, then time
- [x] Page scrolls vertically
- [x] Page items are visually separated

### Tasks:
- [x] Create feature branch
- [x] Create Filter component
- [x] Add filter logic
- [x] Add sort logic
- [x] Add Route
- [x] Create component in Storybook
- [x] Add style
- [x] Test on mobile

### Size: 
large
