### ISSUE TITLE
Add Navigation

### ISSUE THREAD

**Issue by nikkypyra** [nikkypyra/capstone-project#19]
### Value Statement: 
As a **user**, 
I need to be able to **navigate** 
to **access all pages**.

### Description: 
a navigation bar with access to the home page and filter page
<img width="377" alt="nav" src="https://user-images.githubusercontent.com/57285588/81542557-20dc8100-9375-11ea-8037-4927b267415f.png">

### Acceptance criteria:
- [x] The navigation bar is fixed
- [x] Reach pages "/" and "filter" through clicking the navigation buttons

### Tasks:
- [x] Create feature branch
- [x] Add Navigation component to app
- [x] Create component in Storybook
- [x] Add style
- [x] Test on mobile

### Size: 
medium
