### ISSUE TITLE
Task form

### ISSUE THREAD

**Issue by nikkypyra** [nikkypyra/capstone-project#2]
### Value Statement: 
As a **user**, 
I need to **add new tasks to my pets' schedule** 
to **keep track of their daily requirements**.

### Description: 
* A form to add tasks with:
    * An input for the task description
    * An input for the date
    * An input for the time
    * An input for “to be completed by:”
    * A button to submit [Create Task]
* A button linked to create-task page from pet-profile
<img width="440" alt="Story2a" src="https://user-images.githubusercontent.com/57285588/80636111-34c2e180-8a5d-11ea-90db-aa6456ae9d79.png">
<img width="535" alt="Story2b" src="https://user-images.githubusercontent.com/57285588/80627667-8fa20c00-8a50-11ea-8422-d6a6b10df796.png">

### Acceptance criteria:
- [x] The page is found at the path "/create-task”
- [x] The input fields are limited to 100 characters
- [x] The button is disabled until all fields filled
- [x] The form reacts on submit (Enter key or button press)
- [x] Redirected to page with path “/pet-profile” on submit
- [x] Form data saved to local storage
- [x] Checkbox data saved to local storage
- [x] The new task is added to the pet-profile page
- [x] Add button: On click loads path "/create-task”
- [x] App is hosted

### Tasks:
- [x] Create feature branch
- [x] Add TaskForm component to app
- [x] Add SubmitButton component to app
- [x] Add routes
- [x] Create TaskForm component in Storybook
- [x] Create SubmitButton component in Storybook
- [x] Create AddButton component to app
- [x] Create AddButton component in Storybook
- [x] Set up firebase hosting
- [x] Set up local storage
- [x] Add style
- [x] Test on mobile

### Size: 
large
