### ISSUE TITLE
Create account (Authentication)

### ISSUE THREAD

**Issue by nikkypyra** [nikkypyra/capstone-project#20]
### Value Statement: 
As a **user**, 
I need to **save my information in my own account** 
for **privacy and personalization**.

### Description: 
-A login page with a form which includes: email field, password field, login button, signup button
-A signup page with a form which includes: email field, password field, signup button, back link to login page
-A log out link added to header
<img width="369" alt="login" src="https://user-images.githubusercontent.com/57285588/81542588-32be2400-9375-11ea-9fbd-5c009aed5d4f.png">

### Acceptance criteria:
- [x] A users data is only available to that user
- [x] The login page is found at the path "/”
- [x] The signup page is found at the path "/signup”
- [x] Redirected to page with path “/home” on submit of successful login or signup
- [x] The buttons are disabled until all fields filled correctly
- [x] Clicking "Log Out" logs out user
- [x] Receive error alerts if wrong username or password, reset password

### Tasks:
- [x] Create feature branch
- [x] Set up Firebase Authentication
- [x] Connect Firebase Authentication users to Database users
- [x] Connect pets and tasks for users
- [x] Set up Auth Provider/Context
- [x] Set up login, signup, logout functions
- [x] Add data visibility for users functions
- [x] Add Login component 
- [x] Add Login test
- [x] Add Signup component 
- [x] Add dynamic header with "Log Out" for users
- [x] Test on mobile
- [x] Style

### Size: 
x-large
