### ISSUE TITLE
Get pet information and tasks from database

### ISSUE THREAD

**Issue by nikkypyra** [nikkypyra/capstone-project#22]
### Value Statement: 
As a **user**, 
I need to **access and change the information in the app permanently** 
so that **I do not lose any important information**.

### Description: 
No visible changes to app

### Acceptance criteria:
- [x] The data is available on multiple devices and changes are saved

### Tasks:
- [x] Create feature branch
- [x] Set up Firestore
- [x] Add data to Firestore
- [x] Add create, update, delete, read functionality that connects to database
- [x] Test on mobile

### Size: 
large
