### ISSUE TITLE
Edit pet and edit task

### ISSUE THREAD

**Issue by nikkypyra** [nikkypyra/capstone-project#25]
### Value Statement: 
As a **user**, 
I need to be able to **edit my pets and their tasks** 
to **keep the information up to date**.

### Description: 
* A form filled with current information to edit pets with:
    * An input for the pet’s name
    * A preview of current pet photo 
    * A button to upload new pet photo
    * A button to submit [Update Pet]
    * A button to delete the pet
* A button on the home page to reach the update-pet page
* A form filled with current information to edit tasks with:
    * An input for the task description
    * An input for the date
    * An input for the time
    * An input for “to be completed by:”
    * A button to submit [Update Task]
    * A button to delete the task

<img width="361" alt="edit1" src="https://user-images.githubusercontent.com/57285588/82330892-b0240d00-99e3-11ea-9a12-a4c70c3c9106.png">
<img width="360" alt="edit2" src="https://user-images.githubusercontent.com/57285588/82330898-b1edd080-99e3-11ea-92d8-0c2ee08ea04c.png">
<img width="361" alt="edit3" src="https://user-images.githubusercontent.com/57285588/82330902-b31efd80-99e3-11ea-939b-bdbe85272610.png">
<img width="365" alt="edit4" src="https://user-images.githubusercontent.com/57285588/82330905-b3b79400-99e3-11ea-998f-5cbdce282b59.png">

### Acceptance criteria:
- [x] Edit pet button-> on click loads path "....../update-pet”
- [x] The page is found at the path "......./update-pet”
- [x] The button is disabled until name field filled
- [x] The form reacts on submit (Enter key or button press)
- [x] Redirected to page with path “/home” on submit
- [x] Form data saved to database
- [x] The updated pet is visible on the home page
- [x] Edit task button-> on click loads path "....../update-task”
- [x] The page is found at the path "......./update-task”
- [x] The button is disabled until all fields filled
- [x] The form reacts on submit (Enter key or button press)
- [x] Redirected to page with path “/pet/....” on submit
- [x] Form data saved to database
- [x] The updated task is visible on the pet's page

### Tasks:
- [x] Create feature branch
- [x] Add EditPetForm component to app
- [x] Add EditTaskForm component to app
- [x] Add routes
- [x] Add EditButton Component to home page
- [x] Update form data to database
- [x] Add style
- [x] Test on mobile

### Size: 
large
