### ISSUE TITLE
Confirm delete

### ISSUE THREAD

**Issue by nikkypyra** [nikkypyra/capstone-project#26]
### Value Statement: 
As a **user**, 
it would be beneficial to **confirm my removal of pets or tasks from my account** 
to **ensure I don't delete important information accidentally**.

### Description: 
a confirmation alert when deleting a pet or task

### Acceptance criteria:
- [x] There is a confirmation alert when deleting pets or tasks
- [x] The pet or task is not deleted if "cancel" is clicked
- [x] The pet or task is deleted if "ok" is clicked

### Tasks:
- [x] Add delete alert to deletePet and deleteTask with library

### Size: 
small

**Comment by nikkypyra** [comment]
### Value Statement: 
As a **user**, 
it would be beneficial to **confirm my removal of pets or tasks from my account** 
to **ensure I don't delete important information accidentally**.

### Description: 
a confirmation alert when deleting a pet or task

### Acceptance criteria:
- [x] There is a confirmation alert when deleting pets or tasks
- [x] The pet or task is not deleted if "cancel" is clicked
- [x] The pet or task is deleted if "ok" is clicked

### Tasks:
- [x] Add delete alert to deletePet and deleteTask with library

### Size: 
small
