### ISSUE TITLE
Create flexible calendar

### ISSUE THREAD

**Issue by nikkypyra** [nikkypyra/capstone-project#3]
### Value Statement: 
As a **user**, 
I need to **add repeatable tasks to my pet’s schedule** 
so that I **don't have to add the same task every day**.

### Description: 
a calendar to choose multiple dates within the "Date:" portion of the task form.

### Acceptance criteria:
- [ ] The user can choose multiple dates for an event
- [ ] Calendar data saved to local storage

### Tasks:
- [ ] Create feature branch
- [ ] Add every-day-calendar library to app
- [ ] Add calendar component to app
- [ ] Create calendar component in Storybook
- [ ] Add style
- [ ] Test on mobile and desktop

### Size: 
large
