### ISSUE TITLE
Delete Task

### ISSUE THREAD

**Issue by nikkypyra** [nikkypyra/capstone-project#3]
### Value Statement: 
As a **user**, 
I need to **delete tasks from my pet’s schedule** 
to **keep tasks organized**.

### Description: 
a delete button that removes the task
<img width="487" alt="Story3" src="https://user-images.githubusercontent.com/57285588/80639988-1a8c0200-8a63-11ea-945f-0e48a13dbbc4.png">

### Acceptance criteria:
- [ ] onClick the task is no longer visible on the page
- [ ] Task removed from local storage

### Tasks:
- [ ] Create feature branch
- [ ] Add DeleteButton component to app
- [ ] Create component in Storybook
- [ ] Add style
- [ ] Test on mobile and desktop

### Size: 
small
