### ISSUE TITLE
Family Sharing

### ISSUE THREAD

**Issue by nikkypyra** [nikkypyra/capstone-project#34]
### Value Statement: 
As a **user**, 
I need to **share my pets with my family** 
so that we can **delegate the tasks and stay organized**.

### Description: 
-A add-family page with a form which includes: family member's email field, submit button
-A settings page with an overview of current family members and ability to remove them
-Settings added to navigation
<img width="356" alt="settings" src="https://user-images.githubusercontent.com/57285588/82732759-86365780-9d0f-11ea-823a-d58f98589453.png">
<img width="363" alt="settings1" src="https://user-images.githubusercontent.com/57285588/82732763-89c9de80-9d0f-11ea-81eb-45249adb8cae.png">

### Acceptance criteria:
- [x] User can add family members
- [x] A users data is only visible to themselves and their family members
- [x] The add-family page is found at the path "/add-family”
- [x] The settings page is found at the path "/settings”
- [x] The settings page can be reached through the navigation bar
- [x] Redirected to page with path “/settings” on submit of add-family
- [x] The buttons are disabled until all fields filled correctly
- [x] User can delete family members
- [x] Animation is visible on pages and checkboxes

### Tasks:
- [x] Create feature branch
- [x] Set up family in database
- [x] Create add-family logic
- [x] Create delete-family logic
- [x] Add data visibility for users/family functions
- [x] Add Settings component 
- [x] Add JoinFamily component 
- [x] Add unit tests
- [x] Add cypress tests
- [x] Add stories
- [x] Test on mobile
- [x] Style and animation

### Size: 
x-large
