### ISSUE TITLE
Delete task

### ISSUE THREAD

**Issue by nikkypyra** [nikkypyra/capstone-project#4]
### Value Statement: 
As a **user**, 
I need to **delete tasks from my pet’s schedule** 
to **keep tasks organized and up to date**.

### Description: 
a delete button that removes the task
<img width="487" alt="Story3" src="https://user-images.githubusercontent.com/57285588/80639988-1a8c0200-8a63-11ea-945f-0e48a13dbbc4.png">

### Acceptance criteria:
- [x] onClick the task is no longer visible on the page
- [x] Task removed from local storage

### Tasks:
- [x] Create feature branch
- [x] Add DeleteButton component to app
- [x] Create component in Storybook
- [x] Add style
- [x] Test on mobile and desktop

### Size: 
small
