### ISSUE TITLE
Create pet list

### ISSUE THREAD

**Issue by nikkypyra** [nikkypyra/capstone-project#7]
### Value Statement: 
As a **user**, 
I need to have **an overview of my pets** 
to **keep their schedules organized**.

### Description: 
 a scrollable list of pets with their names and photos
![Story #1](https://user-images.githubusercontent.com/57285588/80963712-d5275600-8e0f-11ea-9b25-57bab42bb812.jpeg)

### Acceptance criteria:
- [x] Page includes photos and names of pets
- [x] Page is found at the path “/”
- [x] Page scrolls vertically
- [x] Profiles are visually separated

### Tasks:
- [x] Create feature branch
- [x] Add Home component to app
- [x] Add Router
- [x] Add style
- [x] Test on mobile

### Size: 
small
