### ISSUE TITLE
Create pet form

### ISSUE THREAD

**Issue by nikkypyra** [nikkypyra/capstone-project#8]
### Value Statement: 
As a **user**, 
I need to be able to **add new pets** 
to **keep track of their individual daily requirements**.

### Description: 
* A form to add pets with:
    * An input for the pet’s name
    * A preview of pet photo (placeholder if none)
    * A button to upload pet photo
    * Upload progress % shown while loading
    * A button to submit [Create Pet]
* A button linked to create-task page from pet-profile
![LINDNER](https://user-images.githubusercontent.com/57285588/80964266-d60cb780-8e10-11ea-8937-0ff748df3f75.JPG)
![story3](https://user-images.githubusercontent.com/57285588/80964272-d7d67b00-8e10-11ea-8e61-af63e26fb361.JPG)

### Acceptance criteria:
- [x] Add Pet button-> on click loads path "/create-pet”
- [x] The page is found at the path "/create-pet”
- [x] Upload progress % shown while loading
- [x] The button is disabled until name field filled
- [x] The form reacts on submit (Enter key or button press)
- [x] Redirected to page with path “/” on submit
- [x] Form data saved to local storage
- [x] The new pet is added to the home page

### Tasks:
- [x] Create feature branch
- [x] Add PetForm component to app
- [x] Set up Firebase Storage to store images
- [x] Add route
- [x] Add AddButton Component to home page
- [x] Add form data to local storage
- [x] Add style
- [x] Test on mobile

### Size: 
large
